packaging_format = 2

id = "picodev"
name = "PicoDAV"
description.en = "Single-file WebDAV server, just drop it in a directory!"
description.fr = "Serveur WebDAV mono-fichier, il suffit de le déposer dans un répertoire !"

version = "0.1.7~ynh1"

maintainers = [""]

[upstream]
license = "AGPL-3.0"
website = "https://example.com"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/kd2org/picodav"

[integration]
yunohost = ">= 11.1.13"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/picodav"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.1-fpm"
